### ISSUE TITLE
Progress Bars!

### ISSUE THREAD

**Issue by oscarbranson** [oscarbranson/latools_gui#61]
# Let's connect them up!

## Back-end
Will require some tweaking at my end. **What do you need latools to output to drive a progress bar?**

## Implementation
- [x] latools can work with progress bars other than tqdm
### Working in...
- [x] Despiking
- [x] Autorange
- [x] Background Calculation/Correction
- [x] Ratio
- [x] Calibration

**Comment by oscarbranson** [comment]
At the moment I used `tqdm` to manage the progress bars. Connecting up the pyqt ones will require a bit of re-tooling on my side.

If I've understood [this](https://pythonprogramming.net/progress-bar-pyqt-tutorial/) properly, the progress bar can be driven by any iterable.

I *think* a good option might be to allow a 'pbar' object to be passed to latools processing steps. If unspecified, it will use a default `tqdm` progress bar object, and display as current. If given an object with an 'update' method, it will pass the current % complete to the 'update' method during each iteration.

That work? Can you make all the progress bars have an 'update' method?

**Comment by oscarbranson** [comment]
OK, structure is in place for progress bar updating:

The analyse object now has a has a 'pbar' attribute, which stores the progress bar. When processing occurs a the progress bar is initialised with two arguments - 'total' and 'desc' which describe the total number of items in the bar and give it a label. In every iteration of the process, the progress bar is advanced by 1 using an `.update()` method.

## Minimal Working Example
```python
import time
from tqdm import tqdm

class progress:
    def __init__(self, pbar):
        self.pbar = pbar
    
    def process(self, n=20):
        with self.pbar(total=n, desc='Thing happening') as pbar:
            for i in range(n):
                # work happens here
                time.sleep(0.1)
                pbar.update()
                
prog = progress(pbar=tqdm)

prog.process()
```

### Question:
Can you modify this to work with the PyQt progress bar?

**Comment by oscarbranson** [comment]
I've just been playing around with QProgressBar a bit... I'm not sure the above will work very well with your current setup, because it involves creating a new progress bar instance in each case. Give me some idea for the requirements of the QProgressBar case, and I'll make it work.

**Comment by SimonPetocz** [comment]
I think the above should work great with just a couple of minor tweaks:
Instead of 
`self.pbar(total=n, desc='Thing happening')`
Can we go
`self.pbar.set(total=n, desc='Thing happening')`
And then when the processing has finished, it would be handy to call
`self.pbar.reset()`

The reason is, as you say, it's better if we don't need to create a new pbar object each time, and because I need to instantiate the pbar object with an actual QProgressBar object. So the class would look like this:


```
class ProgressUpdater:

	def __init__(self, progressBar):

		self.total = None
		self.desc = None
		self.value = 0
		self.progressBar = progressBar

	def set(self, total, desc):
		self.total = total
		self.desc = desc
		# QProgressBar works off the difference between a min and max
		self.progressBar.setMinimum(1)
		self.progressBar.setMaximum(total) 

	def update(self):
		self.value += 1
		self.progressBar.setValue(self.value)

	def reset(self):
		self.progressBar.reset()
		self.value = 0
```

This way we can just send the pbar object to the analysis object and have the set(total, desc) update() and reset() calls control the progress bar in the GUI.

**Comment by oscarbranson** [comment]
Yeah that should work. I can just wrap tqdm in a parent object that has set and reset commands. Will get it done today.

**Comment by SimonPetocz** [comment]
Thanks @oscarbranson the progress bars are working now.
There is a potential problem that the pbar parameter is getting written to the log files:

`__init__ :: args=() kwargs={'pbar': <templates.progressUpdater.ProgressUpdater object at 0x1a1cd19fd0>, 'srm_file': None, 'names': 'file_names', 'internal_standard': 'Ca43', 'time_format': None, 'cmap': None, 'srm_identifier': 'STD', 'dataformat': None, 'config': 'DEFAULT', 'errorhunt': False, 'data_folder': './data/', 'extension': '.csv'}`

But we can talk about that Friday

**Comment by oscarbranson** [comment]
Good catch. I'll exclude the pbar argument from logging.

**Comment by oscarbranson** [comment]
@SimonPetocz I've modified logging so it no longer stores the 'pbar' attribute.

This might cause problems at your end when re-creating an analysis from a log file - you'll need to manually pass your progress bar object to latools.analyse, as it won't be included in the log file.

**Comment by oscarbranson** [comment]
Aaalso, can the progress bar remain coloured after it reaches 100%? i.e. only reset it when you advance a stage?

For very fast progress bars, its impossible to tell that it's doing anything!

**Comment by oscarbranson** [comment]
I'm going to reopen this one until we're sure everything working properly with the logging.

**Comment by SimonPetocz** [comment]
Thanks Oscar, that's all really easy to do and it's working great now.
