### ISSUE TITLE
Problems with drop-downs

### ISSUE THREAD

**Issue by oscarbranson** [oscarbranson/latools_gui#78]
I've been noticing some strange behaviour in the drop-down menus. Sporadically, they seem to stop working (they register a click, but don't show any contents).

When it gets in this state, the close button on the program also stops working. No errors output to the terminal. Can't work out why this is happening.

**Comment by SimonPetocz** [comment]
Hi Oscar, that's a tricky one. When the program opens the file browser I sometimes find that suddenly nothing responds, but it goes back to normal when I switch to a different program and back again (like alt + tab). I think this is a Mac specific issue, but it might be related. 
When you run into the problem, does switching make a difference? (Probably not, as you would have switched over to check the terminal output)
Meanwhile I'll do some research.
